# Generated by Django 5.0.4 on 2024-04-27 02:26

import InventoryManagement.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="DeviceConfig",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("device_serial", models.CharField(max_length=50)),
                ("device_cpu", models.CharField(max_length=50)),
                ("device_gpu", models.CharField(blank=True, max_length=50, null=True)),
                ("device_ram", models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name="Location",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("location_name", models.CharField(max_length=128)),
                (
                    "location_desc",
                    models.CharField(blank=True, max_length=200, null=True),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Role",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "role_name",
                    models.CharField(
                        choices=[("user", "User"), ("admin", "Admin")], max_length=50
                    ),
                ),
                ("role_desc", models.CharField(blank=True, max_length=200, null=True)),
            ],
        ),
        migrations.CreateModel(
            name="Device",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("device_name", models.CharField(max_length=100)),
                ("device_type", models.CharField(max_length=50)),
                (
                    "device_desc",
                    models.CharField(blank=True, max_length=200, null=True),
                ),
                ("device_status", models.CharField(max_length=50)),
                (
                    "config",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="InventoryManagement.deviceconfig",
                    ),
                ),
                (
                    "location",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="InventoryManagement.location",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="User",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("approval_status", models.BooleanField(default=False)),
                ("user_fname", models.CharField(max_length=50)),
                ("user_sname", models.CharField(max_length=50)),
                ("user_email", models.EmailField(max_length=254)),
                ("user_phone", models.CharField(max_length=20)),
                (
                    "role",
                    models.ForeignKey(
                        default=InventoryManagement.models.User.get_default_role,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="InventoryManagement.role",
                    ),
                ),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Booking",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("booking_req_date", models.DateField()),
                ("booking_status", models.CharField(max_length=50)),
                ("status_change_date", models.DateTimeField(auto_now_add=True)),
                ("collected_status", models.BooleanField(default=False)),
                ("collected_date", models.DateTimeField(blank=True, null=True)),
                ("device_exp_ret_date", models.DateField()),
                ("device_act_ret_date", models.DateField(blank=True, null=True)),
                (
                    "device",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="InventoryManagement.device",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="InventoryManagement.user",
                    ),
                ),
            ],
        ),
    ]
