# Generated by Django 5.0.4 on 2024-04-30 12:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('InventoryManagement', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='device',
            name='return_day',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='device',
            name='device_status',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='deviceconfig',
            name='device_cpu',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='deviceconfig',
            name='device_ram',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='deviceconfig',
            name='device_serial',
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
