# Generated by Django 5.0.4 on 2024-04-29 18:53

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("InventoryManagement", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="device",
            name="return_day",
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name="device",
            name="device_status",
            field=models.BooleanField(default=False),
        ),
    ]
