# Generated by Django 5.0.4 on 2024-04-30 02:14

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("InventoryManagement", "0002_device_return_day_alter_device_device_status"),
    ]

    operations = [
        migrations.AlterField(
            model_name="deviceconfig",
            name="device_cpu",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name="deviceconfig",
            name="device_ram",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name="deviceconfig",
            name="device_serial",
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
