# Generated by Django 5.0.4 on 2024-04-30 13:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("InventoryManagement", "0003_alter_deviceconfig_device_cpu_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="device",
            name="config",
            field=models.ForeignKey(
                default=1234,
                on_delete=django.db.models.deletion.CASCADE,
                to="InventoryManagement.deviceconfig",
            ),
            preserve_default=False,
        ),
    ]
