# Generated by Django 5.0.4 on 2024-05-02 00:00

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("InventoryManagement", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelManagers(
            name="customuser",
            managers=[],
        ),
    ]
