# Generated by Django 5.0.4 on 2024-05-02 00:15

import InventoryManagement.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("InventoryManagement", "0002_alter_customuser_managers"),
    ]

    operations = [
        migrations.AlterField(
            model_name="booking",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL
            ),
        ),
        migrations.AlterField(
            model_name="customuser",
            name="role",
            field=models.ForeignKey(
                default=InventoryManagement.models.get_user_role,
                on_delete=models.SET(InventoryManagement.models.get_user_role),
                to="InventoryManagement.role",
            ),
        ),
        migrations.AlterField(
            model_name="customuser",
            name="username",
            field=models.CharField(blank=True, default="", max_length=255),
        ),
    ]
