# Generated by Django 5.0.4 on 2024-05-02 00:20

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            "InventoryManagement",
            "0003_alter_booking_user_alter_customuser_role_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="customuser",
            name="username",
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
