# Generated by Django 5.0.4 on 2024-04-30 06:57

import authentication.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0002_alter_customuser_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='role',
            field=models.ForeignKey(default=authentication.models.get_user_role, on_delete=models.SET(authentication.models.get_user_role), to='authentication.role'),
        ),
    ]
